### PR TITLE
Menus

### PR DESCRIPTION
**Pull request by IshaDakota**

### CODE REVIEW

**Comment by IshaDakota** [comment]
Main menu w. dropdowns:

about_us___site-install

**Comment by Shorashim** [comment]
Looks good!

**Comment by IshaDakota** [comment]
@Shorashim I have another idea about the sidebar menu:

Instead of replicating the whole set of links in the top menu, maybe we should just display the second level menu items for the applicable area of the site. For example, on the "Your application" section you would have a menu like this:

Your Application
 - How to Register
 - Start/Update Your Application
 - Application Checklist
 - Important Travel Information
 -Tell your friends

Top  level navigation would remain at the top. 

This is consistent with what israeloutdoors.com does. Thoughts?

**Comment by Shorashim** [comment]
That sounds good to me. As long as it's user-friendly and easy to navigate, I am all for it.

**Comment by IshaDakota** [comment]
OK - I might try to work it up both ways to see what looks best - I still
can't decide in my mind.

**Comment by Shorashim** [comment]
Totally fine. Thank you so much!

**Comment by IshaDakota** [comment]
I think I'm reversing my opinion. I like the way it looks with the full menu on the sidebar, with the submenu items as designed. This way users will probably initially use the menu at the top (because that is what they are used to) and then my turn to the sidebar menu as they navigate throughout the site.

about_us___site-install

I'm going to merge this into the master and if we decide we want to experiment with different styles, we can open up a new issue.

**Comment by Shorashim** [comment]
Looks good!

**Pull request merged**
