### PR TITLE
WIP: About page.

### PR DESCRIPTION
**Pull request by IshaDakota**
#7

### CODE REVIEW

**Comment by IshaDakota** [comment]
banners_and_alerts_and_about_us___site-install

**Comment by IshaDakota** [comment]
banners_and_alerts_and_about_us___site-install

**Comment by Shorashim** [comment]
The alignment looks off on the picture. Please make sure it is formatted as it was in the original design. Thanks!

**Comment by IshaDakota** [comment]
@Shorashim This is set using the  CSS rule:

    background-size: cover; 

It allows background images to cover a changing size space without changing the ratio of the image. The result is that depending on the width of the frame, the image may layout differently. The image you see is zoomed out really far so I could get a wide screenshot. Take a look at it on the DEV site - it looks nice,

**Comment by Shorashim** [comment]
In the thread-there are two images. Are you referencing the most recent one or the one from 3 hours ago? I like how to one from three hours ago looks better. Is that adhering to the changing space? Thanks!

**Comment by IshaDakota** [comment]
@Shorashim Yes, the second version is cropped oddly because I zoomed out dramatically to get a long image. Here it is at at my normal laptop resolution - also more WIP on the testimonial slider and video:
about_us___site-install

**Comment by IshaDakota** [comment]
With sidebar elements: search bar and ad images

about_us___site-install_and_iwiorg_ _bash_ _123x24

**Comment by IshaDakota** [comment]
With un-styled sidebar menu:

about_us___site-install_and_your_application_psd___66_7___rectangle_12__rgb_8____and_style_scss

**Comment by Shorashim** [comment]
Great! Can we make the spacing a bit spread out between the sections on the main page?

**Comment by IshaDakota** [comment]
@Shorashim yes, we will add more space to the headers,

Merging this, if there are any more comments on this page comment on #7 

Also still todo: mailing list signup in the sidebar.

**Pull request merged**
