### PR TITLE
WIP: Trip pages

### PR DESCRIPTION
**Pull request by IshaDakota**

### CODE REVIEW

**Comment by IshaDakota** [comment]
sample_itinerary___site-install

changes from design

**Comment by Shorashim** [comment]
What can we do to make it look like what we had anticipated in the design? This is our favorite page and I don't like it nearly as much without many of the elements. The background image was definitely a highlight and we spent a long time perfecting this page, so it is really important that it is as close to the anticipated design as possible.

**Comment by IshaDakota** [comment]
1. The background image to the title of the day will be impossible to replicate at different widths. Also if you ever decide to change it it will be very costly in terms of development hours to change. If you want it for the desktop width we can just sacrifice mobile view - otherwise this needs complete redesign.

2. Title of page can be whatever you want - it is just inconsistent with other titles (there are a bunch of design inconsistencies which we can review before launch)

3. The "Map Pin" again, impossible to place accurately at multiple widths. - would need design for mobile to achieve close to pixel perfect

4. Only removed triangle pointer from calendar which a) looked very odd, and b) is tricky to implement.

2.

**Comment by IshaDakota** [comment]
trip_options___site-install

**Comment by Shorashim** [comment]
1. Would it be possible to keep the version like we had for desktop at a standard width and have a simplified version still for mobile as a compromise?

2. I want to make sure everything is consistent, so let's go over that tomorrow to ensure it happens

3. Same question as #1 

4. Why did it look add? Just in implementation or on the design? We liked it on the design.

**Comment by IshaDakota** [comment]
1. Yes - but please be warned - any time you will want to change this - it will be $$$ - Michael and Michal should know that. Will not be ready tomorrow - when we reviewed we did not see all of the backgrounds - it's very labor intensive.

2. OK

3. same deal as # 1 - more than doubling development hours.

4. It's my opinion that it looks strange - but to me the whole page looks very busy and there are multiple indications of which day you are on - seems dizzy. Implementation is tricky, because it's outside the frame, but we can do.

**Comment by IshaDakota** [comment]
trip_dates___site-install

**Comment by Shorashim** [comment]
I just spoke to Michael. I have a few questions in regards to how to move this forward efficiently:

-In terms of the whole page, can we find a middle ground? I think this version looks basic and we want to ensure that our new website is dynamic and has unique elements. 

-When you say it is very labor intensive, what exactly does that mean? How long would it take to have the page ready with the individualized background images for each day? Please keep in mind that Tuesday was our absolute latest expected launch and timing is extremely sensitive for this project.

-How much money would it be to change? We haven't changed anything like this on our old website, so I am not sure that is relevant, but I want to make sure I have as much information as possible

-How long would it take for the map pins? I am more comfortable with simplifying this aspect than the others

-In terms of implementation being tricky for the angled "Day X" piece, how long would this take to do? 

I am going to send you a larger email now, but we need to ensure that this website goes live within our time frame.

**Pull request merged**
