### PR TITLE
WIP: Application Pages

### PR DESCRIPTION
**Pull request by IshaDakota**

### CODE REVIEW

**Comment by IshaDakota** [comment]
how_to_register___site-install_and_your_application_psd___200___copy__rgb_8___

**Comment by IshaDakota** [comment]
@shorashim what is the text for this page?

your_applicattion___site-install

**Comment by IshaDakota** [comment]
application_checklist___site-install

**Comment by IshaDakota** [comment]
@Shorashim - note the expanded menu for the Application section. Some of the titles wrap lines. Do you think we could shorten them rather than make them smaller?

application_checklist___site-install

**Comment by Shorashim** [comment]
Can we keep the longer titles but just change on the menu? Ex. Your Application Checklist can become Checklist on the menu. Any suggestions for the other one? If this isn't sensible, let me know

**Comment by IshaDakota** [comment]
@Shorashim do you mean different titles for the menu on the side and the menu on top? If so, those are actually two different styled outputs of the same menu - but we could possibly change that. 

For maintenance, I'm a little wary of having too many menus that you need to change individually when/if you make changes.

**Comment by Shorashim** [comment]
That makes sense. I am not completely sold on changing the names, just because I think it is direct and explanatory now & I could see it being unclear. However, if you have any suggestions, I am definitely open to hearing them. Is it possible for the submenu items to be smaller or would that look weird?

**Comment by Shorashim** [comment]
Reached out to Daniel in regards to "Start/Update Your Application"

**Comment by IshaDakota** [comment]
How about removing the word "Your" ?
application_checklist___site-install

**Comment by Shorashim** [comment]
This looks good!

**Pull request merged**
