### PR TITLE
Shorashim Live Elements

### PR DESCRIPTION
**Pull request by IshaDakota**

### CODE REVIEW

**Comment by IshaDakota** [comment]
site-install

**Comment by IshaDakota** [comment]
home___birthright_israel__shorashim

**Comment by IshaDakota** [comment]
@Shorashim, please:
1. approve the layout at http://test-israel-with-israelis.pantheon.io/ 
2. Indicate which 10 instagram photos you want in the initial rollout.

3. I will change #taglit to #birthright

**Comment by Shorashim** [comment]
Approved.

Let's do these:
1. U of I girls in hats 
1. Marzipan
2. Dead Sea
3. Quote about adventure and energy
4. Hummus
5. Girl in water in Tel Aviv
6. Selfie on masada
7. Tel Aviv
8. Girls on boys shoulder in water

Do those all work?

**Pull request merged**
